version: '3.8'
services:
  database:
    image: postgres
  rabbitmq:
    image: rabbitmq:3.11-management
  gateway-api:
    image: gateway-api-image
  contact-api:
    image: contact-api-image
    depends_on:
      - database
      - gateway-api
  report-api:
    image: report-api-image
    depends_on:
      - rabbitmq
      - database
      - gateway-api