version: '3.8'
services:
  database:
    container_name: pb-postgre
    ports:
      - "5432:5432"
    volumes:
      - pb-postgre-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    networks:
        - pb-network
  rabbitmq:
    container_name: pb-rabbitmq
    ports:
        - "5672:5672"
        - "15672:15672"
    networks:
       - pb-network
  gateway-api:
   image: gateway-api-image
   build: 
      context: .
      dockerfile: src/apigateway/Phonebook.ApiGateway/Dockerfile
   ports:
     - "7036:80"
   networks:
     - pb-network
  contact-api:
    image: contact-api-image
    container_name: ContactApi
    build: 
      context: .
      dockerfile: src/services/contact/Contact.API/Dockerfile
    ports:
       - "7038:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:ContactConnectionString= Server=host.docker.internal;Port=5432;Database=PB-ContactDb;Username=postgres;Password=123456;
    depends_on:
      - database
    networks:
       - pb-network
  report-api:
    image: report-api-image
    container_name: ReportApi
    build: 
      context: .
      dockerfile: src/services/report/Report.API/Dockerfile
    ports:
       - "7083:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMq:Url=host.docker.internal
      - ConnectionStrings:ReportConnectionString= Server=host.docker.internal;Port=5432;Database=PB-ReportDb;Username=postgres;Password=123456;
      - ContactApi:BaseUrl=contactapi
    depends_on:
      - rabbitmq
      - database
    networks:
       - pb-network
volumes:
   pb-postgre-volume :
    driver:  local
networks:
    pb-network:
        external: true
        