version: '3.8'
services:
  database:
    image: postgres
  rabbitmq:
    image: rabbitmq:3.11-management
  gateway-api:
    image: gateway-api-image
    build: 
      context: .
      dockerfile: services/apigateway/Phonebook.ApiGateway/Dockerfile
  contact-api:
    image: contact-api-image
    build: 
      context: .
      dockerfile: services/contact/Contact.API/Dockerfile
    depends_on:
      - database
  report-api:
    image: report-api-image
    build: 
      context: .
      dockerfile: services/report/Report.API/Dockerfile
    depends_on:
      - rabbitmq
      - database